# ------------------------------------------------------------
# SERVER CONFIG
# ------------------------------------------------------------
server.port=8081
spring.application.name=jwt-demo
spring.main.web-application-type=servlet

# ------------------------------------------------------------
# KEYCLOAK CONFIG
# ------------------------------------------------------------
keycloak.realm=my-realm
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}

# Token & revoke endpoints used by KeycloakAuthService
keycloak.token-url=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
keycloak.logout-url=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/revoke

# ------------------------------------------------------------
# RESOURCE SERVER (JWT)
# ------------------------------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}

# ------------------------------------------------------------
# ACTUATOR + PROMETHEUS
# ------------------------------------------------------------
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.metrics.web.server.request.autotime.enabled=true
management.metrics.web.server.request.autotime.percentiles=0.5,0.95,0.99

# ------------------------------------------------------------
# OBSERVABILITY (OpenTelemetry & Tracing)
# ------------------------------------------------------------
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

# ------------------------------------------------------------
# RATE LIMITING (Bucket4j)
# ------------------------------------------------------------
#logging.level.org=DEBUG
#logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.giffing.bucket4j=DEBUG

# --- Spring Cache ---
spring.cache.type=jcache
spring.cache.jcache.provider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
spring.cache.cache-names[0]=filterConfigCache
spring.cache.cache-names[1]=loginBuckets
spring.cache.cache-names[2]=adminBuckets
spring.cache.caffeine.spec=maximumSize=1000000,expireAfterAccess=3600s

# --- Enable Bucket4j ---
bucket4j.enabled=true
bucket4j.cache-to-use=jcache
bucket4j.filter-config-caching-enabled=true
bucket4j.filter-config-cache-name=filterConfigCache

# Limit /auth/login for client spring-app: 5 requests per minute
# The id of the filter. This field is mandatory when configuration caching is enabled and should always be a unique string.
bucket4j.filters[0].id=loginfilter
bucket4j.filters[0].cache-name=loginBuckets
bucket4j.filters[0].url=/api/auth/login
#bucket4j.filters[0].rate-limits[0].expression=clientId == 'spring-app'
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=5
bucket4j.filters[0].rate-limits[0].bandwidths[0].refill-capacity=5
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=MINUTES
bucket4j.filters[0].rate-limits[0].bandwidths[0].initial-capacity=5
bucket4j.filters[0].rate-limits[0].bandwidths[0].refill-speed=INTERVAL

# Limit /api/admin: 20 requests per second
# The id of the filter.
bucket4j.filters[1].id=adminfilter
bucket4j.filters[1].cache-name=adminBuckets
bucket4j.filters[1].url=/api/admin
bucket4j.filters[1].rate-limits[0].bandwidths[0].capacity=20
bucket4j.filters[1].rate-limits[0].bandwidths[0].refill-capacity=20
bucket4j.filters[1].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[1].rate-limits[0].bandwidths[0].unit=MINUTES
bucket4j.filters[1].rate-limits[0].bandwidths[0].initial-capacity=20
bucket4j.filters[1].rate-limits[0].bandwidths[0].refill-speed=INTERVAL
